name: Unzip and Remove ZIP

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check files
        run: |
          ls -lah

      - name: Test zip
        run: |
          unzip -t moji-v1.26.6.9.zip

      - name: Extract
        run: |
          unzip -o moji-v1.26.6.9.zip -d .
          rm moji-v1.26.6.9.zip

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Extract moji zip" || exit 0
          git push
