name: 解压缩并删除 ZIP 文件

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 检查文件
        run: |
          ls -lah

      - name: 解压 ZIP 文件
        run: |
          unzip -O GBK -o moji-v1.26.6.9.zip -d .
          rm -f moji-v1.26.6.9.zip

      - name: 提交解压后的文件
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "解压 moji-v1.26.6.9.zip 并删除压缩包" || echo "没有需要提交的更改"

          git push
